# 公共配置文件
spring:
  # session 失效时间（分钟）
  session:
    timeout: 86400
    # todo sz※  Spring默认将Session存储在服务器中，通过store-type配置将Session存储到Redis数据库中
    store-type: redis
  profiles:
    active: dev
  application:
    name: partner-system-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.253.128:3306/partenerSystem?serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/partenerSystem?serverTimezone=Asia/Shanghai
    username: root
    password: Eplugger231

#todo sz※ SpringBoot2.6以上版本，在整合Knife4j时,需要添加下面的mvc路径配置防止出现空指针
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 1
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
#  todo sz※  domain用于控制Cookie的作用范围（不同域名之间是无法共享Cookie的），允许会话Cookie在本地主机和您指定的域上设置。
#  只能解决多个前端访问一个后端时携带Cookie 如果多个后端共享Session时，需要使用到分布式Session了？
        domain: localhost
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
#    mybatis-plus开启查询日志，线上环境时可以关闭，开发调试时使用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
